repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.30.0
  hooks:
  - id: gitleaks
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shellcheck
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/espressif/conventional-precommit-linter
  rev: v1.11.0
  hooks:
    - id: conventional-precommit-linter
      stages: [commit-msg]
      args:
        - --types=feat,fix,docs,style,refactor,test,chore,ci,build,perf,remove,revert,change
        - --allow-breaking
        - --subject-min-length=15
- repo: https://github.com/rvben/rumdl-pre-commit
  rev: v0.0.187  # Use the latest release tag
  hooks:
    - id: rumdl
      # To only check (default):
      # args: []
      # To automatically fix issues:
      args: [--fix]


minimum_pre_commit_version: 3.3.0
default_install_hook_types: [pre-commit, commit-msg]


#Type: Indicates the nature of the change. Common types include:
#    feat: A new feature
#    fix: A bug fix
#    docs: Documentation changes
#    style: Code style changes, Linter fixes (formatting, missing semicolons, etc.)
#    refactor: Code refactoring without adding features or fixing bugs
#    test: Adding or modifying tests
#    chore: Miscellaneous tasks like build processes or auxiliary tools
#    ci: Changes to continuous integration scripts
