version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
- KeePass
- KeePassXC
- fluffypeople
- managesieve
- assertj
- atmf
- febrildur
- fifesoft
- jasypt
- managesievej
- openrewrite
- rsyntaxtextarea
- sieveeditor
ignoreWords: []
import: []
