version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aatext
  - assertj
  - atmf
  - choco
  - Dawt
  - Dskip
  - Dsun
  - Dswing
  - elif
  - fakeroot
  - febrildur
  - fifesoft
  - flathub
  - fluffypeople
  - jasypt
  - jpackage
  - KeePass
  - KeePassXC
  - managesieve
  - managesievej
  - metainfo
  - openrewrite
  - rsyntaxtextarea
  - sieveeditor
  - sieveprofiles
  - temurin
  - wixtoolset
ignoreWords: []
import: []
